### PR TITLE
Fix ignore-path description

### PR DESCRIPTION
**Pull request by roggervalf**
This is a docs fix, just deleting the "=" character in ignore-path description

### CODE REVIEW

**Comment by roggervalf** [comment]
@azz could you please take a look on this :eyes:

**Comment by roggervalf** [comment]
@azz could you please take a look on this :eyes:

**Comment by roggervalf** [comment]
@azz could you please take a look on this 👀

**Comment by azz** [comment]
Thanks, and sorry I missed this!

**Pull request merged**
