### PR TITLE
Mercurial support

### PR DESCRIPTION
**Pull request by TobiasTimm**
This is still WIP. 

I really like the idea of this project. I recently added hg support to husky on my own fork, so I wanted to implement the hg part in pretty-quick too.

Like I said this PR is still work in progress, but feel free to comment and share your opinion.

### CODE REVIEW

**Comment by azz** [comment]
This is awesome! I hope I made the SCM API generic enough for this to work, though Mercurial is more similar to git than other SCMs. 

Could you also add it to the README.md and add some package.json `keywords`?

**Comment by azz** [comment]
Hey @TobiasTimm, just wondering what the status of your work is here? Would love to get Mercurial support landed!

**Comment by TobiasTimm** [comment]
Hey @azz I was in the hospital last week and still need some time recover at home. I hope you don't mind it. I will try to implement the mecurial support asap after that.

**Comment by azz** [comment]
No hurry, was just following up. Take your time and get well first ☺

**Comment by TobiasTimm** [comment]
Hey @azz, I've fixed the tests for hg but it's still experimental. I still need to get the time to test it with a real hg repo.

**Comment by azz** [comment]
Looking good to me. I'm not too familiar with mercurial so I'll defer to your manual testing results.

**Comment by TobiasTimm** [comment]
@azz tested it with a local hg repo and fixed some stuff. Should be ready now :smile:

**Comment by azz** [comment]
Thank you!

**Pull request merged**
