### PR TITLE
feat: --no-restage flag for skipping re-stage step in staged mode (#39)

### PR DESCRIPTION
**Pull request by benwiley4000**

### CODE REVIEW

**Comment by benwiley4000** [comment]
Oops, mis-typed the name of the flag in the docs. I'll force push the corrected version.

**Comment by benwiley4000** [comment]
All good now!

**Comment by azz** [comment]
Looks like the tests fail now. Could you investigate that, and also add a new test for this flag? 

```
 FAILsrc/__tests__/scm-git.test.js
●with git › with --staged stages fully-staged files
expect(jest.fn()).toHaveBeenCalledWith(expected)
    Expected mock function to have been called with:
["add", "./raz.js"] as argument 2, but it was called with["ls-files", "--others", "--exclude-standard"].
["add", "./raz.js"] as argument 2, but it was called with["diff", "--name-only", "--diff-filter=ACMRTUB"].
["add", "./raz.js"] as argument 2, but it was called with["diff", "--name-only", "--cached", "--diff-filter=ACMRTUB", "banana"].
 172 |    prettyQuick('root' { since:'banana' staged:true });
 173 |
> 174 |    expect(execa.sync).toHaveBeenCalledWith('git' ['add''./raz.js'] {
 175 |      cwd:'/'
 176 |    });
 177 |    expect(execa.sync).not.toHaveBeenCalledWith('git' ['add''./foo.md'] {
at Object.test (src/__tests__/scm-git.test.js:174:34)
```

**Comment by benwiley4000** [comment]
Oops! I'll check it out, thanks for flagging.

Le mar. 18 sept. 2018 06 h 04, Lucas Azzola <notifications@github.com> a
écrit :

**Comment by benwiley4000** [comment]
@azz I added tests, and a commit at the end to change "foo.md" to "foo.js" since I assumed that was a typo. If not, I can get rid of that commit.

**Comment by azz** [comment]
Thanks!

**Comment by benwiley4000** [comment]
Thank _you_! :)

**Pull request merged**
