### PR TITLE
chore: Update dependencies

### LINKED ISSUE #102: Upgrade prettier dependency to 2.0
Prettier recently upgraded to 2.0: https://prettier.io/blog/2020/03/21/2.0.0.html. We should upgrade the dependency in pretty-quick to avoid local prettier clashes.

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
BREAKING CHANGE: Node >=10.13.0 is required
BREAKING CHANGE: Prettier ^2.0.0 is required

---

Closes #101
Closes #102

### CODE REVIEW

**Comment by cgfarmer4** [comment]
+1 for new prettier

**Comment by MichaelDeBoey** [comment]
@cgfarmer4 prettier@2.x requires node@10.13.x

**Comment by cgfarmer4** [comment]
I just ran it on 8 🤔

**Comment by MichaelDeBoey** [comment]
https://prettier.io/blog/2020/03/21/2.0.0.html#drop-support-for-node-versions-older-than-10-6908httpsgithubcomprettierprettierpull6908-by-fiskerhttpsgithubcomfisker

**Comment by azz** [comment]
@MichaelDeBoey Thanks for this PR and apologies for the delay, I was taking a break from OSS.

This all looks good, and especially after the delay in reviewing, I don't have any issues in pushing a v3 with these changes.

I've just tinkered with the `semantic-release` setup (bump from v11 to v15), so hopefully this goes out without a hitch. 🤞

**Pull request merged**
